### ISSUE TITLE
Add support for GRPC for nginx Ingress

### ISSUE THREAD

**Issue by orlovmyk** [DefGuard/deployment#39]
Currently as I understand you are testing only with traefik, so it's only supported ingress

I use Nginx Ingress (official one, not k8s)
https://artifacthub.io/packages/helm/nginx/nginx-ingress

My solution for now is to create custom ingress to route traffic
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: defguard-custom-ingress-grpc
  namespace: "base"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.org/grpc-services: defguard-grpc
spec:
  ingressClassName: nginx
  rules:
  - host: defguard-custom-grpc.myk.pp.ua
    http:
      paths:
      - backend:
          service:
            name: defguard-grpc
            port:
              number: 50055
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - defguard-custom-grpc.myk.pp.ua
    secretName: defguard-custom-ingress-grpc-tls
```

And also I had to enable http2 according to https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource#listeners

```
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: "base"
data:
  http2: "true"
```
